server:
    port: 8081

security:
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri: https://someplace/oauth/access_token
      userAuthorizationUri: https://somplace/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
